TITLE ESTUDO AULA 12
.MODEL SMALL

PULALINHA MACRO
    PUSH DX
    PUSH AX
    MOV DL,10
    MOV AH,02
    INT 21H
    POP AX
    POP DX
    ENDM

.DATA
    VETOR DB 31H,32H,34H,35H,36H,?,'$'

.CODE
MAIN PROC
    MOV AX,@DATA
    MOV DS,AX
    MOV ES,AX

    LEA SI,VETOR+4 ;APONTA PRO 6 PRA MOVER ELE PRIMEIRO PRO ?
    LEA DI,VETOR+5 ;APONTA PRO ? PRA MOVER TD UM PRO LADO
    
    STD ; SETA DF, QUANDO 1 A DIREÇÃO DO VETOR É DO CONTRA

    MOV CX,3 
    REP MOVSB ;FUNCIONA Q NEM LOOP, MOVE UM VALOR DO VETOR DE SI (ONDE TA ORIGINALMENTE) PRA DI Q TA UM A FRENTE
              ;DPS DISSO, ELE DIMINUI AMBOS SI E DI, DEIXANDO O ESPAÇO LIVRE PRA 5 IR PRA ONDE 6 TAVA
    
    MOV BYTE PTR [DI],33H ;NO ESPAÇO ALOCADO ENTRE 2 E 4 DPS DOS DESLOCAMENTOS DOS OUTROS, BOTA 3 ONDE DI TERMINOU (3)
    
    LEA DX,VETOR
    MOV AH,09
    INT 21H

    MOV AH,4CH
    INT 21H


MAIN ENDP
END MAIN